# Generated by Django 5.2.11 on 2026-04-07 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('url_lusofona', models.URLField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='docentes/')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('instituicao', models.CharField(max_length=200)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('url_certificado', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Formação',
                'verbose_name_plural': 'Formações',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Licenciatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sigla', models.CharField(blank=True, max_length=20)),
                ('grau', models.CharField(blank=True, max_length=100)),
                ('ects', models.IntegerField(blank=True, null=True)),
                ('duracao_anos', models.IntegerField(blank=True, null=True)),
                ('url_lusofona', models.URLField(blank=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Licenciatura',
                'verbose_name_plural': 'Licenciaturas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MakingOf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('decisoes_tomadas', models.TextField()),
                ('erros_correcoes', models.TextField(blank=True)),
                ('uso_ia', models.TextField(blank=True)),
                ('foto_caderno', models.ImageField(blank=True, null=True, upload_to='makingof/')),
                ('data_registo', models.DateField(auto_now_add=True)),
                ('entidade_relacionada', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Making Of',
                'verbose_name_plural': 'Making Of',
                'ordering': ['entidade_relacionada', 'data_registo'],
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tecnologias/')),
                ('url_oficial', models.URLField(blank=True)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('nivel_interesse', models.IntegerField(default=3)),
                ('pontos_destaque', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tecnologia',
                'verbose_name_plural': 'Tecnologias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('autor', models.CharField(max_length=300)),
                ('orientador', models.CharField(blank=True, max_length=300)),
                ('licenciatura_nome', models.CharField(blank=True, max_length=300)),
                ('ano', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('url_pdf', models.URLField(blank=True, max_length=500, null=True)),
                ('url_imagem', models.URLField(blank=True, max_length=500, null=True)),
                ('resumo', models.TextField(blank=True)),
                ('classificacao', models.IntegerField(default=3)),
            ],
            options={
                'verbose_name': 'TFC',
                'verbose_name_plural': 'TFCs',
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('formacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='portfolio.formacao')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['formacao'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.TextField(blank=True)),
                ('conceitos_aplicados', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='projetos/')),
                ('url_github', models.URLField(blank=True)),
                ('url_demo', models.URLField(blank=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('tecnologias', models.ManyToManyField(blank=True, related_name='projetos', to='portfolio.tecnologia')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('nivel', models.CharField(blank=True, max_length=50)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('projetos', models.ManyToManyField(blank=True, related_name='competencias', to='portfolio.projeto')),
                ('tecnologias', models.ManyToManyField(blank=True, related_name='competencias', to='portfolio.tecnologia')),
            ],
            options={
                'verbose_name': 'Competência',
                'verbose_name_plural': 'Competências',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('ects', models.IntegerField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='ucs/')),
                ('docentes', models.ManyToManyField(blank=True, related_name='unidades_curriculares', to='portfolio.docente')),
                ('licenciatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_curriculares', to='portfolio.licenciatura')),
            ],
            options={
                'verbose_name': 'Unidade Curricular',
                'verbose_name_plural': 'Unidades Curriculares',
                'ordering': ['ano', 'semestre'],
            },
        ),
        migrations.AddField(
            model_name='projeto',
            name='uc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to='portfolio.unidadecurricular'),
        ),
    ]
