# Generated by Django 5.2.11 on 2026-04-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MakingOf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='making_of/')),
                ('data_registo', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Making Of',
                'verbose_name_plural': 'Making Of',
                'ordering': ['-data_registo'],
            },
        ),
    ]
