# Generated by Django 5.2.11 on 2026-04-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('resumo', models.TextField()),
                ('autor', models.CharField(max_length=200)),
                ('ano', models.IntegerField()),
                ('area', models.CharField(max_length=100)),
                ('classificacao', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('url_repositorio', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'TFC',
                'verbose_name_plural': 'TFCs',
                'ordering': ['-ano'],
            },
        ),
    ]
