# Generated by Django 5.2.11 on 2026-04-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('autor', models.CharField(max_length=300)),
                ('orientador', models.CharField(blank=True, max_length=300)),
                ('licenciatura_nome', models.CharField(blank=True, max_length=300)),
                ('ano', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('url_pdf', models.URLField(blank=True, max_length=500, null=True)),
                ('url_imagem', models.URLField(blank=True, max_length=500, null=True)),
                ('resumo', models.TextField(blank=True)),
                ('classificacao', models.IntegerField(default=3)),
            ],
            options={
                'verbose_name': 'TFC',
                'verbose_name_plural': 'TFCs',
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=300)),
                ('ano_curricular', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('ects', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('duracao', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Unidade Curricular',
                'verbose_name_plural': 'Unidades Curriculares',
                'ordering': ['ano_curricular', 'semestre'],
            },
        ),
    ]
