# Generated by Django 5.2.11 on 2026-04-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_tfc'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=300)),
                ('ano_curricular', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('ects', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('duracao', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Unidade Curricular',
                'verbose_name_plural': 'Unidades Curriculares',
                'ordering': ['ano_curricular', 'semestre'],
            },
        ),
    ]
