# Generated by Django 5.2.11 on 2026-04-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_tfc_unidadecurricular'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='makingof',
            options={'ordering': ['entidade_relacionada', 'data_registo'], 'verbose_name': 'Making Of', 'verbose_name_plural': 'Making Of'},
        ),
        migrations.RemoveField(
            model_name='makingof',
            name='imagem',
        ),
        migrations.AddField(
            model_name='makingof',
            name='decisoes_tomadas',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='makingof',
            name='entidade_relacionada',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='makingof',
            name='erros_correcoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='makingof',
            name='foto_caderno',
            field=models.ImageField(blank=True, null=True, upload_to='makingof/'),
        ),
        migrations.AddField(
            model_name='makingof',
            name='uso_ia',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='makingof',
            name='data_registo',
            field=models.DateField(auto_now_add=True),
        ),
    ]
