# Generated by Django 5.2.11 on 2026-04-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_makingof_options_remove_makingof_imagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('instituicao', models.CharField(max_length=200)),
                ('ano', models.IntegerField()),
                ('url', models.URLField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='certificados/')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('nivel', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Competência',
                'verbose_name_plural': 'Competências',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('instituicao', models.CharField(max_length=200)),
                ('ano', models.IntegerField()),
                ('descricao', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Formação',
                'verbose_name_plural': 'Formações',
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='Licenciatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sigla', models.CharField(blank=True, max_length=20)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Licenciatura',
                'verbose_name_plural': 'Licenciaturas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Tecnologia',
                'verbose_name_plural': 'Tecnologias',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='makingof',
            name='decisoes_tomadas',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.TextField(blank=True)),
                ('ano', models.IntegerField()),
                ('url', models.URLField(blank=True)),
                ('tecnologias', models.ManyToManyField(blank=True, to='portfolio.tecnologia')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-ano'],
            },
        ),
    ]
